import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next App by Aryan Arora',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='relative'>
        {/* <Navbar /> */}
        {children}
        {/* <Footer /> */}
        </body>
    </html>
  )
}
